added tests for CheckLists and CreateNewCheck methods
digitalocean/pydo pull request #219
Opened 2023-10-01 11:33 UTC by Sanket-0510

refers issue #213 
Add Mocked Tests: Uptime
add tests for uptime.lists_check , uptime.create_check

In API resources the method name is given by the name checks_list(), but the actual method name is list_checks(), thats a point to be noted and hence I have used the method list_check() while writing the tests, correct me if I am wrong.

2023-10-01 11:36 UTC, Sanket-0510 commented
@danaelhe am I on the right path.
Right now have added test's for two methods, need a green flag from your side to add the remaining tests for the uptime, thank you.

2023-10-02 16:52 UTC, danaelhe commented
Looks great!! Apologies, I should've included in the instructions but we lint our tests with the python package black. Currently, the "lint" test is failing for this PR but it's a super easy fix.  If you run: poetry run black tests while in the pydo directory, it will automatically reformat the files and the "lint" test will pass. So just run that command and push up the changes and the lint tests will pass 👍

2023-10-02 16:54 UTC, danaelhe requested changes
Looks SO GOOD! Just need to push up the commit that fixes the lint tests 👍

2023-10-02 19:01 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +def test_uptime_check_lists_get(mock_client: Client, mock_client_url):
if you run `make lint-tests`, you'll see a bunch of errors asking:
`tests/mocked/test_uptime.py:42:0: C0116: Missing function or method docstring (missing-function-docstring)`
This is super easy fix, you'll just have to add "docstrings" under the function, as such:
```suggestion
def test_check_state_get(mock_client: Client, mock_client_url):
    """Mock Uptime Check State"""
```

2023-10-02 19:02 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +def test_check_state_get(mock_client: Client, mock_client_url):
if you run make lint-tests, you'll see a bunch of errors asking:
tests/mocked/test_uptime.py:42:0: C0116: Missing function or method docstring (missing-function-docstring)
This is super easy fix, you'll just have to add "docstrings" under the function, as such:

```suggestion
def test_check_state_get(mock_client: Client, mock_client_url):
    """Mock Uptime Check State"""
```

2023-10-02 19:03 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +def test_update_check_put(mock_client: Client, mock_client_url):
add docstring here as well:
```suggestion
def test_update_check_put(mock_client: Client, mock_client_url):
    """Mock Uptime Check Update"""
```

2023-10-02 19:04 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +def test_list_all_alerts_get(mock_client: Client, mock_client_url):
Add docstring here as well:
```suggestion
def test_list_all_alerts_get(mock_client: Client, mock_client_url):
    """Mock Uptime Check List All Alerts"""
```

2023-10-02 19:05 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +def test_update_alert_put(mock_client: Client, mock_client_url):
```suggestion
def test_update_alert_put(mock_client: Client, mock_client_url):
    """Mock Uptime Update Alert"""
```

2023-10-02 19:06 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +        f"{mock_client_url}/v2/uptime/checks/{CHECK_ID}/state",
```suggestion
        f"{mock_client_url}/v2/uptime/checks/{check_id}/state",
```

2023-10-02 19:07 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +    get_res = mock_client.uptime.get_check_state(CHECK_ID)
```suggestion
    get_res = mock_client.uptime.get_check_state(check_id)
```

2023-10-02 19:10 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +    CHECK_ID = "4de7ac8b-495b-4884-9a69-1050c6793cd6"
```suggestion
    check_id = "4de7ac8b-495b-4884-9a69-1050c6793cd6"
```

2023-10-02 19:11 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +    put_res = mock_client.uptime.update_check(CHECK_ID, body=req)
```suggestion
    put_res = mock_client.uptime.update_check(check_id, body=req)
```

2023-10-02 19:11 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +    CHECK_ID = "4de7ac8b-495b-4884-9a69-1050c6793cd6"
```suggestion
    check_id = "4de7ac8b-495b-4884-9a69-1050c6793cd6"
```

2023-10-02 19:11 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +    get_res = mock_client.uptime.list_alerts(CHECK_ID)
```suggestion
    get_res = mock_client.uptime.list_alerts(check_id)
```

2023-10-02 19:11 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +    CHECK_ID = "4de7ac8b-495b-4884-9a69-1050c6793cd6"
```suggestion
    check_id = "4de7ac8b-495b-4884-9a69-1050c6793cd6"
```

2023-10-02 19:11 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +    ALERT_ID= "17f0f0ae-b7e5-4ef6-86e3-aa569db58284"
```suggestion
    alert_id= "17f0f0ae-b7e5-4ef6-86e3-aa569db58284"
```

2023-10-02 19:11 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +        f"{mock_client_url}/v2/uptime/checks/{CHECK_ID}/alerts/{ALERT_ID}",
```suggestion
        f"{mock_client_url}/v2/uptime/checks/{check_id}/alerts/{ALERT_ID}",
```

2023-10-02 19:12 UTC, danaelhe commented on tests/mocked/test_uptime.py
> +        CHECK_ID, ALERT_ID, body=req)
```suggestion
        check_id, alert_id, body=req)
```

2023-10-03 06:41 UTC, Sanket-0510 commented
Fixed the lint errors but when I run the command `poetry run black tests` and formatted the code. Running `make lint-tests` I am getting an error or a warning maybe,  am not clear: "line too long" like please look into this and suggest the further changes if any required.

2023-10-03 15:51 UTC, danaelhe approved these changes
AWESOME job!! This is good to merge and ship 🚀 

Thank you so much for your contribution!

2023-10-03 15:51 UTC, merged